import { Button } from '@mantine/core';
import Head from 'next/head';
import Image from 'next/image';
import About from '../components/About';
import Nav from '../components/Nav';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='text-sky-500'>Hello</div>
      <Button> Hello </Button>
      <Nav></Nav>
      <About></About>
    </div>
  );
}
